"""
Django settings for bcse_site project.

Generated by 'django-admin startproject' using Django 3.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from .base_settings import *
import datetime
import pytz

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5rzd8xmwjp_&3txyul)evn(v*p@g&2aa%ax9t=5n$%cas&l=s#'

ALLOWED_HOSTS = ['*']
SITE_ID = 1

LOGIN_URL = '/signin'

CSRF_TRUSTED_ORIGINS = [
    "https://bcse-stage.northwestern.edu",
    "https://bcse.northwestern.edu",
]

# Application definition

INSTALLED_APPS = [
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sites',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'bcse_app',
    'localflavor',
    'storages',
    'ckeditor',
    'ckeditor_uploader',
    'compressor',
    'django_crontab',
    'dbbackup', #django-dbbackup
    'django_recaptcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'bcse_app.middleware.AjaxDetectionMiddleware',
    'bcse_app.middleware.UpdateSession',
    'bcse_app.middleware.OnlineNowMiddleware',
    'bcse_app.middleware.NextParameterMiddleware',
    'bcse_app.middleware.DomainMiddleware',


]

ROOT_URLCONF = 'bcse_site.urls'

AWS_S3_REGION_NAME = 'us-east-1'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = 'public-read'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region_name": AWS_S3_REGION_NAME,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

#AWS_S3_SECURE_URLS = True       # use http instead of https

DBBACKUP_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DBBACKUP_STORAGE_OPTIONS = {
    'access_key': AWS_ACCESS_KEY_ID,
    'secret_key': AWS_SECRET_ACCESS_KEY,
    'bucket_name': AWS_DBBACKUP_BUCKET_NAME,
    'default_acl': 'private',
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bcse_app.context_processors.partners_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'bcse_site.wsgi.application'


CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_UPLOAD_SLUGIFY_FILENAME = False
CKEDITOR_RESTRICT_BY_USER = True
#CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_FILENAME_GENERATOR = 'bcse_site.utils.get_filename'
CKEDITOR_CONFIGS = {
    'default': {
        'removePlugins': 'stylesheetparser',
        'toolbar': [
             ['Bold', 'Italic', 'Underline','-', 'Subscript', 'Superscript', '-', 'NumberedList',
            'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter',
            'JustifyRight', 'JustifyBlock', 'Image', 'Table', 'HorizontalRule', 'SpecialChar', 'Mathjax', 'Iframe', '-', 'NLModels',
             '-','Link', 'Unlink'] ,
             "/",
             ['Styles', 'Format', 'Font', 'FontSize', 'TextColor',
             'BGColor', 'Maximize', 'ShowBlocks', '-','Source','-','RemoveFormat']
        ],
        'height': '100%',
        'width': '100%',
        'allowedContent': True,
        'mathJaxLib': '//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_HTMLorMML',
        'codeSnippet_theme': 'monokai_sublime',
        'extraPlugins': ','.join(
            ['mathjax', 'codesnippet', 'uploadwidget', 'scayt', 'autogrow', 'uploadwidget', 'ajax', 'iframedialog']
        ),
        'autoGrow_onStartup': True,
        'scayt_autoStartup': True,
        'scayt_sLang': 'en_US',
        'disableNativeSpellChecker': False,
    },
    'message_ckeditor': {
        'removePlugins': 'stylesheetparser',
        'toolbar': [
             ['Bold', 'Italic', 'Underline','-', 'Subscript', 'Superscript', '-', 'NumberedList',
            'BulletedList', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter',
            'JustifyRight', 'JustifyBlock', 'Table', 'SpecialChar', 'Mathjax', '-', 'Link', 'Unlink'] ,
             "/"
        ],
        'height': '100%',
        'width': '100%',
        'allowedContent': True,
        'extraPlugins': ','.join(
            ['scayt', 'autogrow']
        ),
        'autoGrow_onStartup': True,
        'scayt_autoStartup': True,
        'scayt_sLang': 'en_US',
        'disableNativeSpellChecker': False,
        'editorplaceholder': 'Type your message here'
    },
    'resource_url_ckeditor': {
        'removePlugins': 'stylesheetparser',
        'toolbar': [
             ['BulletedList', '-', 'Link'] ,
             "/"
        ],
        'height': '50%',
        'width': '100%',
        'allowedContent': True,
        'extraPlugins': ','.join(
            ['scayt', 'autogrow']
        ),
        'autoGrow_onStartup': True,
        'scayt_autoStartup': True,
        'scayt_sLang': 'en_US',
        'disableNativeSpellChecker': False,
    },
    'simple_ckeditor': {
        'removePlugins': 'stylesheetparser',
        'toolbar': [
             ['Bold', 'Italic', 'Underline','-', 'Subscript', 'Superscript', '-', 'NumberedList', 'BulletedList'], "/"
        ],
        'height': '100%',
        'width': '100%',
        'allowedContent': True,
        'extraPlugins': ','.join(
            ['scayt', 'autogrow']
        ),
        'autoGrow_onStartup': True,
        'scayt_autoStartup': True,
        'autoGrow_maxHeight': '200',
        'scayt_sLang': 'en_US',
        'disableNativeSpellChecker': False,
    },

}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

COMPRESS_ENABLED = True

COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc {infile} {outfile}'),
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
)

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

DATE_INPUT_FORMATS = ['%B %d, %Y']
TIME_INPUT_FORMATS = ['%I:%M %p']

USE_I18N = True

USE_L10N = False

USE_TZ = True

ONLINE_THRESHOLD = 60

DEFAULT_ITEMS_PER_PAGE = 25

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "..", "www", "static")
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

##############################
#BAXTER BOX CONFIGURATION
#DELIVERY MONDAY AND FRIDAY
BAXTER_BOX_DELIVERY_DAYS = [0, 4]
#RETURN MONDAY AND FIRDAY
BAXTER_BOX_RETURN_DAYS = [0, 4]
#MIN RESERVATION LENGTH 1 WEEK
BAXTER_BOX_MIN_RESERVATION_DAYS = 7
#MAX RESERVATION LENGTH 4 WEEK
BAXTER_BOX_MAX_RESERVATION_DAYS = 21
#MIN ADVANCE RESERVATION 7 DAYS
BAXTER_BOX_MIN_ADVANCE_RESERVATION_DAYS = 14
#MAX ADVANCE RESERVATION 6 MONTHS
BAXTER_BOX_MAX_ADVANCE_RESERVATION_DAYS = 180
#ADVANCE RESERVATION REMINDER EMAIL 30 DAYS
BAXTER_BOX_RESERVATION_REMINDER_DAYS = 30

REQUIRE_PROFILE_UPDATE = True
#PROFILE UPDATE CUTOFF DATE = AUG 01
PROFILE_UPDATE_CUTOFF_MONTH = '08'
PROFILE_UPDATE_CUTOFF_DAY = '01'

CRONJOBS = [
    # run cron at 1 am to backup database
    ('0 1 * * *', 'bcse_app.cron.backup_db', '>> /srv/project/logs/cron.log'),
    # run cron at 2 am to export reservations to excel
    ('0 2 * * *', 'bcse_app.cron.export_reservations', '>> /srv/project/logs/cron.log'),
    # run cron at 3 am to export activities to excel
    ('0 3 * * *', 'bcse_app.cron.export_activities', '>> /srv/project/logs/cron.log'),
    # run cron every 5 minutes to send scheduled workshop emails
    ('*/5 * * * *', 'bcse_app.cron.send_workshop_emails', '>> /srv/project/logs/cron.log'),

]

