# Generated by Django 3.2.11 on 2022-01-04 16:53

import bcse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of Equipment Type', max_length=256)),
                ('icon', models.ImageField(blank=True, help_text='Upload an image at least 400x289 in resolution that represents this equipment type', null=True, upload_to=bcse_app.models.upload_file_to)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of Equipment', max_length=256)),
                ('status', models.CharField(choices=[('U', 'Unavilable'), ('A', 'Available')], max_length=1)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='bcse_app.equipmenttype')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
