# Generated by Django 3.2.11 on 2022-01-05 16:24

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0002_auto_20220105_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of Workshop Type', max_length=256)),
                ('icon', models.ImageField(blank=True, help_text='Upload an image that represents this Workshop Type', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('workshop_type', models.CharField(choices=[('I', 'In-Person'), ('V', 'Virtual'), ('H', 'Hybrid')], max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='workshop_type',
        ),
        migrations.DeleteModel(
            name='WorkshopType',
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop', to='bcse_app.workshopcategory'),
            preserve_default=False,
        ),
    ]
