# Generated by Django 3.2.11 on 2022-01-05 16:47

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0003_auto_20220105_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Consumable Kit', max_length=256)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image that represents this Consumable Kit', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workshopcategory',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='equipmenttype',
            old_name='icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='equipmenttype',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='workshopcategory',
            old_name='icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='workshopcategory',
            old_name='title',
            new_name='name',
        ),
    ]
