# Generated by Django 3.2.11 on 2022-01-06 14:01

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0004_auto_20220105_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Activity', max_length=256)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image that represents this Activity', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='bcse_app.EquipmentType')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Consumable Kit', max_length=256)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image that represents this Consumable Kit', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending')], default='R', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_workshops', to='bcse_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('registration_type', models.CharField(choices=[('R', 'Register'), ('A', 'Apply')], max_length=1)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum capacity for this workshop. Leave blank for unlimited capacity', null=True)),
                ('enable_waitlist', models.BooleanField(default=False)),
                ('waitlist_capacity', models.IntegerField(blank=True, help_text='Capacity for the waitlist. Leave blank for unlimited waitlist capacity', null=True)),
                ('open_date', models.DateTimeField(blank=True, help_text='The date registration is open. Leave blank if registration is always open', null=True)),
                ('close_date', models.DateTimeField(blank=True, help_text='The date registration is closed. Leave blank if registration is always open', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('registrants', models.ManyToManyField(null=True, through='bcse_app.Registration', to='bcse_app.UserProfile')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsumableKit',
        ),
        migrations.AddField(
            model_name='workshop',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Workshop end date', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='location',
            field=models.CharField(default='on campus', help_text='Workshop location', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Workshop start date', null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image that represents this Workshop Category', null=True, upload_to=bcse_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='workshopcategory',
            name='name',
            field=models.CharField(help_text='Name of Workshop Category', max_length=256),
        ),
        migrations.AddField(
            model_name='workshopregistration',
            name='workshop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bcse_app.workshop'),
        ),
        migrations.AddField(
            model_name='registration',
            name='workshop_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrants', to='bcse_app.workshopregistration'),
        ),
        migrations.AddField(
            model_name='activity',
            name='kit',
            field=models.OneToOneField(help_text='Kit required for this activity', on_delete=django.db.models.deletion.CASCADE, to='bcse_app.activitykit'),
        ),
        migrations.AddField(
            model_name='activity',
            name='workshop',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='bcse_app.Workshop'),
        ),
    ]
