# Generated by Django 3.2.11 on 2022-01-06 15:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0005_auto_20220106_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='activitykit',
            name='status',
        ),
        migrations.AddField(
            model_name='equipment',
            name='hub',
            field=models.CharField(choices=[('N', 'North'), ('C', 'Chicago')], default='C', help_text='Hub for Equipment', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshopregistration',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_activity', models.BooleanField(default=False)),
                ('other_activity_name', models.CharField(help_text='Name of the other activity', max_length=256)),
                ('need_activity_kit', models.BooleanField(default=True)),
                ('num_of_classes', models.IntegerField()),
                ('num_of_students', models.IntegerField()),
                ('additional_help', models.BooleanField(default=False)),
                ('need_equipment', models.BooleanField(default=True)),
                ('delivery_date', models.DateTimeField(help_text='The date the equipment/kit will be delivered/picked up')),
                ('return_date', models.DateTimeField(blank=True, help_text='The date the equipment will be returned', null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, help_text='Any additional information', null=True)),
                ('status', models.CharField(choices=[('U', 'Unconfirmed'), ('C', 'Confirmed'), ('O', 'Checked Out'), ('I', 'Checked In'), ('N', 'Cancelled')], default='C', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcse_app.activity')),
                ('equipment', models.ManyToManyField(blank=True, null=True, to='bcse_app.Equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to='bcse_app.userprofile')),
            ],
            options={
                'ordering': ['delivery_date'],
            },
        ),
    ]
