# Generated by Django 3.2.11 on 2022-01-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0006_auto_20220106_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='enable_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='delivery_date',
            field=models.DateField(help_text='The date the equipment/kit will be delivered/picked up'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, help_text='Any additional information', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True, help_text='The date the equipment will be returned', null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(blank=True, help_text='Workshop end date', null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_date',
            field=models.DateField(blank=True, help_text='Workshop start date', null=True),
        ),
    ]
