# Generated by Django 3.2.11 on 2022-01-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0007_auto_20220106_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='bcse_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='workshop_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrants', to='bcse_app.workshopregistration', verbose_name='Workshop'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('O', 'Other Professional'), ('S', 'Staff')], max_length=1),
        ),
    ]
