# Generated by Django 3.2.11 on 2022-01-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0008_auto_20220107_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='other_activity_name',
            field=models.CharField(blank=True, help_text='Name of the other activity', max_length=256, null=True),
        ),
    ]
