# Generated by Django 3.2.11 on 2022-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0009_alter_reservation_other_activity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
    ]
