# Generated by Django 3.2.11 on 2022-01-13 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0010_equipmenttype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                ('registration_type', models.CharField(choices=[('R', 'Register'), ('A', 'Apply')], max_length=1, null=True)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum capacity for this workshop. Leave blank for unlimited capacity', null=True)),
                ('enable_waitlist', models.BooleanField(default=False)),
                ('waitlist_capacity', models.IntegerField(blank=True, help_text='Capacity for the waitlist. Leave blank for unlimited waitlist capacity', null=True)),
                ('open_date', models.DateTimeField(blank=True, help_text='The date registration is open. Leave blank if registration is always open', null=True)),
                ('close_date', models.DateTimeField(blank=True, help_text='The date registration is closed. Leave blank if registration is always open', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='registration',
            name='workshop_registration',
        ),
        migrations.DeleteModel(
            name='WorkshopRegistration',
        ),
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='registrants',
            field=models.ManyToManyField(null=True, through='bcse_app.Registration', to='bcse_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='workshop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='bcse_app.workshop'),
        ),
        migrations.AddField(
            model_name='registration',
            name='workshop_registration_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrants', to='bcse_app.workshopregistrationsetting', verbose_name='Workshop'),
            preserve_default=False,
        ),
    ]
