# Generated by Django 3.2.11 on 2022-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0011_auto_20220113_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistrationsetting',
            name='status',
        ),
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='registrants',
            field=models.ManyToManyField(blank=True, null=True, through='bcse_app.Registration', to='bcse_app.UserProfile'),
        ),
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('R', 'Register'), ('A', 'Apply')], max_length=1, null=True),
        ),
    ]
