# Generated by Django 3.2.11 on 2022-01-14 18:58

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0012_auto_20220113_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Team Member', max_length=256)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=256)),
                ('position', models.CharField(help_text='Position of the Team Member', max_length=256)),
                ('organization', models.CharField(help_text='Org. of the Team Member', max_length=256)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of this team member', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
