# Generated by Django 3.2.11 on 2022-01-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0013_auto_20220114_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='validation_code',
            field=models.CharField(default='ABCD', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('P', 'Other Professional'), ('S', 'BCSE Staff')], max_length=1),
        ),
    ]
