# Generated by Django 3.2.11 on 2022-02-23 17:58

import bcse_app.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcse_app', '0014_auto_20220118_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='hub',
        ),
        migrations.AddField(
            model_name='workshop',
            name='sub_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='confirmation_message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='city',
            field=models.CharField(default='Chicago', help_text='City', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='state',
            field=localflavor.us.models.USStateField(default='IL', help_text='State', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='street_address_1',
            field=models.CharField(default='2020 Campus Dr', help_text='Street Address 1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workplace',
            name='zip_code',
            field=models.CharField(help_text='Zip Code of Work Place', max_length=256),
        ),
        migrations.CreateModel(
            name='TeacherLeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the teacher leader', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('first_name', models.CharField(help_text='First name of the teacher', max_length=256)),
                ('last_name', models.CharField(help_text='Last name of the teacher', max_length=256)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.workplace')),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bcse_app.workshop')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
