# Generated by Django 3.2.11 on 2022-02-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0015_auto_20220223_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Workshop end time', null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Workshop start time', null=True),
        ),
    ]
