# Generated by Django 3.2.11 on 2022-02-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0016_auto_20220223_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='close_date',
            field=models.DateField(blank=True, help_text='The date registration is closed. Leave blank if registration is always open', null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='open_date',
            field=models.DateField(blank=True, help_text='The date registration is open. Leave blank if registration is always open', null=True),
        ),
    ]
