# Generated by Django 3.2.11 on 2022-02-23 19:07

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0017_auto_20220223_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the teacher', max_length=256)),
                ('last_name', models.CharField(help_text='Last name of the teacher', max_length=256)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the teacher leader', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.workplace')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='TeacherLeaderInfo',
        ),
        migrations.AddField(
            model_name='workshop',
            name='teacher_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.teacherleader'),
        ),
    ]
