# Generated by Django 3.2.11 on 2022-02-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0018_auto_20220223_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcategory',
            name='need_teacher_info',
            field=models.BooleanField(default=False),
        ),
    ]
