# Generated by Django 3.2.11 on 2022-02-24 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0019_workshopcategory_need_teacher_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='teacher_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.teacherleader'),
        ),
    ]
