# Generated by Django 3.2.11 on 2022-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0020_alter_workshop_teacher_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopcategory',
            name='need_teacher_info',
        ),
    ]
