# Generated by Django 3.2.11 on 2022-03-02 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0021_remove_workshopcategory_need_teacher_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='workshop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_setting', to='bcse_app.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('workshop_registration_setting', 'user')},
        ),
    ]
