# Generated by Django 3.2.11 on 2022-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0022_auto_20220302_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='survey_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
