# Generated by Django 3.2.11 on 2022-03-15 20:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0024_workshopcategory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConfirmationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending')], max_length=1, unique=True)),
                ('confirmation_message', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration_status'],
            },
        ),
        migrations.RemoveField(
            model_name='workshopregistrationsetting',
            name='confirmation_message',
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending')], default='R', max_length=1),
        ),
    ]
