# Generated by Django 3.2.11 on 2022-03-16 12:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0025_auto_20220315_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending')], max_length=1, unique=True)),
                ('email_subject', models.CharField(max_length=256)),
                ('email_message', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registration_status'],
            },
        ),
        migrations.DeleteModel(
            name='RegistrationConfirmationMessage',
        ),
    ]
