# Generated by Django 3.2.11 on 2022-03-24 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0026_auto_20220316_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleader',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherleader',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
