# Generated by Django 3.2.11 on 2022-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0027_auto_20220324_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationemailmessage',
            name='include_calendar_invite',
            field=models.BooleanField(default=False),
        ),
    ]
