# Generated by Django 3.2.11 on 2022-04-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0028_registrationemailmessage_include_calendar_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grades_taught',
            field=models.CharField(choices=[('E', 'Elementary School'), ('M', 'Middle School'), ('H', 'High School'), ('O', 'Other')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='iein',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(help_text='Name of Work Place', max_length=256),
        ),
    ]
