# Generated by Django 3.2.11 on 2022-04-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0029_auto_20220406_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grades_taught',
            field=models.CharField(blank=True, choices=[('E', 'Elementary School'), ('M', 'Middle School'), ('H', 'High School'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('A', 'BCSE Admin'), ('T', 'K-12 Teacher or Administrator'), ('P', 'Other Professional'), ('S', 'BCSE Staff')], max_length=1),
        ),
    ]
