# Generated by Django 3.2.11 on 2022-04-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0030_auto_20220415_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
