# Generated by Django 3.2.11 on 2022-04-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0033_auto_20220418_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='hub',
        ),
    ]
