# Generated by Django 3.2.11 on 2022-04-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0034_remove_equipment_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('D', 'Cancelled'), ('I', 'Checked In'), ('O', 'Checked Out'), ('R', 'Confirmed'), ('U', 'Unconfirmed')], default='C', max_length=1),
        ),
    ]
