# Generated by Django 3.2.11 on 2022-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0035_alter_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='additional_help',
            new_name='additional_help_needed',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='need_activity_kit',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='need_equipment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='activity_kit_not_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment_not_needed',
            field=models.BooleanField(default=False),
        ),
    ]
