# Generated by Django 3.2.11 on 2022-04-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0036_auto_20220420_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for displaying on the calendar', max_length=256, null=True),
        ),
    ]
