# Generated by Django 3.2.11 on 2022-05-03 17:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0039_alter_reservation_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_messages', to='bcse_app.userprofile')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_messages', to='bcse_app.reservation')),
                ('viewed_by', models.ManyToManyField(blank=True, null=True, to='bcse_app.UserProfile')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
