# Generated by Django 3.2.11 on 2022-05-04 17:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0040_reservationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmessage',
            name='message',
            field=ckeditor.fields.RichTextField(help_text='Type your message here'),
        ),
    ]
