# Generated by Django 3.2.11 on 2022-05-04 18:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0041_alter_reservationmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
