# Generated by Django 3.2.11 on 2022-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0042_equipmenttype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, help_text='Any additional information', max_length=2048, null=True),
        ),
    ]
