# Generated by Django 3.2.11 on 2022-05-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0043_alter_reservation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
