# Generated by Django 3.2.11 on 2022-05-27 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0044_auto_20220520_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Workshop end date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Workshop start date'),
            preserve_default=False,
        ),
    ]
