# Generated by Django 3.2.11 on 2022-06-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0046_workshopcategory_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='meetup_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
