# Generated by Django 3.2.11 on 2022-06-29 17:25

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0048_auto_20220629_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Partner', max_length=256)),
                ('blurb', models.CharField(help_text='Short callout blurb', max_length=1024)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of this partner', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('url', models.URLField()),
                ('order', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
