# Generated by Django 3.2.11 on 2022-07-12 17:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0049_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Survey', max_length=256)),
                ('survey_type', models.CharField(choices=[('A', 'Async Learning'), ('C', 'Case Study'), ('O', 'Other')], max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('order', models.IntegerField()),
                ('component_type', models.CharField(choices=[('IN', 'Info'), ('DD', 'Drop Down'), ('MC', 'Multiple Choice'), ('MS', 'Multi-Select'), ('CB', 'Checkbox'), ('TF', 'Textfield'), ('TA', 'Textarea'), ('FI', 'File Upload'), ('DT', 'Date'), ('EM', 'Email'), ('UL', 'URL')], default='IN', max_length=2)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('options', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_context', to='bcse_app.survey')),
            ],
            options={
                'ordering': ['page', 'order'],
                'unique_together': {('survey', 'page', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SurveyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_instance', to='bcse_app.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_survey', to='bcse_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('responseFile', models.FileField(blank=True, null=True, upload_to='')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='bcse_app.surveyinstance')),
                ('survey_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='bcse_app.surveycomponent')),
            ],
        ),
    ]
