# Generated by Django 3.2.11 on 2022-07-12 18:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0050_survey_surveycomponent_surveyinstance_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyinstance',
            name='id',
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='surveycomponent',
            name='component_type',
            field=models.CharField(choices=[('IN', 'Info'), ('DD', 'Drop Down'), ('MC', 'Multiple Choice'), ('MS', 'Multi-Select'), ('TF', 'Textfield'), ('TA', 'Textarea'), ('FI', 'File Upload'), ('DT', 'Date'), ('EM', 'Email'), ('UL', 'URL')], default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='surveycomponent',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_component', to='bcse_app.survey'),
        ),
    ]
