# Generated by Django 3.2.11 on 2022-07-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0051_auto_20220712_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='survey_component',
        ),
        migrations.DeleteModel(
            name='SurveyInstance',
        ),
        migrations.DeleteModel(
            name='SurveyResponse',
        ),
    ]
