# Generated by Django 3.2.11 on 2022-07-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0053_surveyresponse_surveysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='ip_address',
            field=models.GenericIPAddressField(default='2601:155:4300:a520:b17b:8e61:abe5:68b7'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveysubmission',
            name='status',
            field=models.CharField(choices=[('I', 'In Progress'), ('S', 'Submitted'), ('R', 'Reviewed')], default='I', max_length=1),
        ),
    ]
