# Generated by Django 3.2.11 on 2022-07-13 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0054_auto_20220713_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
