# Generated by Django 3.2.11 on 2022-07-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0055_auto_20220713_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='term_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surveysubmission',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submission', to='bcse_app.survey'),
        ),
    ]
