# Generated by Django 3.2.11 on 2022-07-28 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0056_auto_20220728_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='nid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
