# Generated by Django 3.2.11 on 2022-08-04 18:30

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0057_workshop_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Block title', max_length=256)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this block', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('button_text', models.CharField(blank=True, max_length=256, null=True)),
                ('button_url', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.IntegerField()),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='teacherleader',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
    ]
