# Generated by Django 3.2.11 on 2022-08-04 19:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0058_auto_20220804_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageblock',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
