# Generated by Django 3.2.11 on 2022-08-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0059_alter_homepageblock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='resource_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='registrationemailmessage',
            name='registration_status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended')], max_length=1, unique=True),
        ),
    ]
