# Generated by Django 3.2.11 on 2022-09-22 18:27

import bcse_app.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0060_auto_20220810_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandalonePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title', max_length=256)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this page', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('button_text', models.CharField(blank=True, max_length=256, null=True)),
                ('button_url', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
