# Generated by Django 3.2.11 on 2022-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0061_standalonepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonepage',
            name='image_position',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1),
        ),
    ]
