# Generated by Django 3.2.11 on 2022-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0062_standalonepage_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonepage',
            name='url_alias',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
