# Generated by Django 3.2.11 on 2022-10-31 15:42

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0064_auto_20221018_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deliver_to_workplace',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ReservationDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(help_text='Street Address 1', max_length=256)),
                ('street_address_2', models.CharField(blank=True, help_text='Street Address 2', max_length=256, null=True)),
                ('city', models.CharField(help_text='City', max_length=256)),
                ('state', localflavor.us.models.USStateField(help_text='State', max_length=2)),
                ('zip_code', models.CharField(help_text='Zip Code', max_length=256)),
                ('latitude', models.CharField(blank=True, max_length=256, null=True)),
                ('longitude', models.CharField(blank=True, max_length=256, null=True)),
                ('time_from_base', models.CharField(blank=True, max_length=256, null=True)),
                ('distance_from_base', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='bcse_app.reservation')),
            ],
        ),
    ]
