# Generated by Django 3.2.11 on 2022-10-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0065_auto_20221031_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='deliver_to_workplace',
        ),
    ]
