# Generated by Django 3.2.11 on 2022-10-31 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0066_remove_reservation_deliver_to_workplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationdeliveryaddress',
            options={'ordering': ['reservation__id']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to='bcse_app.userprofile'),
        ),
    ]
