# Generated by Django 3.2.11 on 2022-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0067_auto_20221031_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleader',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
