# Generated by Django 3.2.11 on 2023-01-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0068_teacherleader_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaxterBoxBlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Blackout start date')),
                ('end_date', models.DateField(help_text='Blackout end date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
            },
        ),
    ]
