# Generated by Django 3.2.11 on 2023-03-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0070_reservation_more_num_of_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='admin_notes',
            field=models.CharField(blank=True, help_text='Notes only admins can add/view', max_length=2048, null=True),
        ),
    ]
