# Generated by Django 3.2.11 on 2023-04-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0071_reservation_admin_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Color', max_length=256)),
                ('color', models.CharField(help_text='Hex code of the Color', max_length=8, unique=True)),
                ('description', models.CharField(help_text='Describe the types of reservations this color will be applied to', max_length=512)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='teacherleader',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.reservationcolor'),
        ),
    ]
