# Generated by Django 3.2.11 on 2023-04-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0072_auto_20230405_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            "update bcse_app_reservation set email_sent=TRUE"
        ),
    ]
