# Generated by Django 3.2.11 on 2023-05-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0074_cancelled_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='teacher_leaders',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, related_name='workshops', to='bcse_app.TeacherLeader'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('N', 'Cancelled'), ('I', 'Checked In'), ('O', 'Checked Out'), ('R', 'Confirmed'), ('U', 'Unconfirmed')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='teacher_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop', to='bcse_app.teacherleader'),
        ),
    ]
