# Generated by Django 3.2.11 on 2023-05-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0075_auto_20230524_1143'),
    ]

    operations = [
        migrations.RunSQL(
                "insert into bcse_app_workshop_teacher_leaders (workshop_id, teacherleader_id) select id, teacher_leader_id from bcse_app_workshop where teacher_leader_id is not null"
            ),
    ]
