# Generated by Django 3.2.11 on 2023-05-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0076_auto_20230524_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='teacher_leader',
        ),
    ]
