# Generated by Django 3.2.11 on 2023-06-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0077_remove_workshop_teacher_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='enable_waitlist',
            field=models.BooleanField(default=True),
        ),
    ]
