# Generated by Django 3.2.11 on 2023-06-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0079_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.survey'),
        ),
    ]
