# Generated by Django 3.2.11 on 2023-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0079_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_release_complete',
            field=models.BooleanField(default=False),
        ),
    ]
