# Generated by Django 3.2.11 on 2023-06-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0080_workshopregistrationsetting_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('A', 'Async Learning'), ('C', 'Case Study'), ('W', 'Workshop Application'), ('O', 'Other')], max_length=1),
        ),
        migrations.CreateModel(
            name='WorkshopApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcse_app.surveysubmission')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcse_app.registration')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('registration', 'application')},
            },
        ),
    ]
