# Generated by Django 3.2.11 on 2023-06-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0081_auto_20230626_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_to_registration', to='bcse_app.surveysubmission'),
        ),
        migrations.AlterField(
            model_name='workshopapplication',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_to_application', to='bcse_app.registration'),
        ),
    ]
