# Generated by Django 3.2.11 on 2023-06-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0082_auto_20230626_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_setting', to='bcse_app.survey'),
        ),
    ]
