# Generated by Django 3.2.11 on 2023-07-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0083_alter_workshopregistrationsetting_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopregistrationsetting',
            name='survey_url',
        ),
    ]
