# Generated by Django 3.2.11 on 2023-07-31 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0080_userprofile_photo_release_complete'),
        ('bcse_app', '0084_remove_workshopregistrationsetting_survey_url'),
    ]

    operations = [
    ]
