# Generated by Django 3.2.11 on 2023-08-01 17:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0086_alter_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='equipment',
            new_name='equipment_mapping',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='workshop',
        ),
        migrations.AddField(
            model_name='activity',
            name='manuals_resources',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter a list of urls for instruction manuals and resoruces', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='materials_equipment',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Enter a list of materials the Baxter Center provides, equipment the users can borrow and materials the user has to arrange themselves', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Describe the activity', null=True),
        ),
    ]
