# Generated by Django 3.2.11 on 2023-08-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0087_auto_20230801_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
