# Generated by Django 3.2.11 on 2023-08-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0090_auto_20230809_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='bcse_app.BaxterBoxSubCategory'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='bcse_app.BaxterBoxSubCategory'),
        ),
    ]
