# Generated by Django 3.2.11 on 2023-09-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0091_auto_20230809_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='inventory',
            field=models.TextField(blank=True, help_text='Consumable Kit inventory', null=True),
        ),
    ]
