# Generated by Django 3.2.11 on 2023-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0092_activity_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='display_date',
            field=models.CharField(blank=True, help_text='For multi-day workshop, enter start and end times for each day', max_length=2048, null=True),
        ),
    ]
