# Generated by Django 3.2.11 on 2023-09-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0093_workshop_display_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='display_date',
            field=models.TextField(blank=True, help_text='For multi-day workshop, enter start and end times for each day', null=True),
        ),
    ]
