# Generated by Django 3.2.11 on 2023-09-14 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0095_alter_workshop_display_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('A', 'Async Learning'), ('C', 'Case Study'), ('W', 'Workshop Application'), ('B', 'Baxter Box Feedback'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='display_date',
            field=models.TextField(blank=True, help_text='For multi-day workshop, enter start and end times for each day', null=True),
        ),
        migrations.CreateModel(
            name='ReservationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_to_reservation', to='bcse_app.surveysubmission')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_to_feedback', to='bcse_app.reservation')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('reservation', 'feedback')},
            },
        ),
    ]
