# Generated by Django 3.2.11 on 2023-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0097_reservation_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='feedback_status',
            field=models.CharField(choices=[('E', 'Email Sent'), ('I', 'Feedback In Progress'), ('S', 'Feedback Submitted')], max_length=1, null=True),
        ),
    ]
