# Generated by Django 3.2.11 on 2023-09-29 15:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0098_alter_reservation_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='inventory',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Consumable Kit inventory', null=True),
        ),
    ]
