# Generated by Django 3.2.11 on 2023-10-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0099_alter_activity_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherleader',
            options={'ordering': ['teacher__user__last_name', 'teacher__user__first_name']},
        ),
        migrations.RemoveField(
            model_name='teacherleader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacherleader',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacherleader',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacherleader',
            name='school',
        ),
        migrations.AddField(
            model_name='teacherleader',
            name='teacher',
            field=models.ForeignKey(default=881, on_delete=django.db.models.deletion.CASCADE, to='bcse_app.userprofile'),
            preserve_default=False,
        ),
    ]
