# Generated by Django 3.2.11 on 2023-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0100_auto_20231013_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='feedback_email_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='feedback_email_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='teacher_leaders',
            field=models.ManyToManyField(blank=True, null=True, related_name='workshops', to='bcse_app.TeacherLeader'),
        ),
    ]
