# Generated by Django 3.2.11 on 2023-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0103_baxterboxblackoutmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcolor',
            name='target',
            field=models.CharField(choices=[('R', 'Reservation'), ('K', 'Activity Kit'), ('B', 'Both')], default='R', max_length=1),
        ),
    ]
