# Generated by Django 3.2.11 on 2023-11-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0104_reservationcolor_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.reservationcolor'),
        ),
    ]
