# Generated by Django 3.2.11 on 2023-11-07 16:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0105_activity_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Inventory notes', null=True),
        ),
    ]
