# Generated by Django 3.2.11 on 2023-11-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0106_activity_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationcolor',
            name='description',
            field=models.CharField(help_text='Describe the types of reservations/kit this color will be applied to', max_length=512),
        ),
    ]
