# Generated by Django 3.2.11 on 2023-11-14 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0107_alter_reservationcolor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='kit_unit_price',
            field=models.FloatField(blank=True, help_text='Unit price for the kit', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
