# Generated by Django 3.2.11 on 2023-11-14 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0108_activity_kit_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='unit_price',
            field=models.FloatField(blank=True, help_text='Unit price for the equipment', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
