# Generated by Django 3.2.11 on 2023-11-15 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0109_equipmenttype_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='kit_unit_price',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='activity',
            name='kit_unit_cost',
            field=models.FloatField(blank=True, help_text='Unit cost for the kit', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='unit_cost',
            field=models.FloatField(blank=True, help_text='Unit cost for the equipment', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
