# Generated by Django 3.2.11 on 2023-11-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0110_auto_20231115_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaxterBoxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2048)),
                ('message_type', models.CharField(choices=[('B', 'Blackout Message'), ('D', 'Date Rule')], default='B', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='I', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['message_type'],
            },
        ),
        migrations.DeleteModel(
            name='BaxterBoxBlackoutMessage',
        ),
    ]
