# Generated by Django 3.2.11 on 2023-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0112_auto_20231129_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('V', 'Veg'), ('N', 'Non_veg'), ('D', 'Dairy-Free'), ('G', 'Gluten-Free')], help_text='Your dietary preference will be saved in your profile', max_length=1, null=True),
        ),
    ]
