# Generated by Django 3.2.11 on 2023-11-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0113_alter_userprofile_dietary_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, help_text='Your dietary preference will be saved in your profile', max_length=256, null=True),
        ),
    ]
