# Generated by Django 3.2.11 on 2023-12-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0115_alter_partner_blurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='blurb',
        ),
    ]
