# Generated by Django 3.2.11 on 2023-12-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0116_remove_partner_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
