# Generated by Django 3.2.11 on 2023-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0117_survey_email_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='email_confirmation_message',
            field=models.CharField(blank=True, help_text='Confirmation message to send via email', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='email_confirmation',
            field=models.BooleanField(default=False, help_text='Email confirmation is only sent if the user is logged in while filling out the survey or there is in email field component in the survey.'),
        ),
    ]
