# Generated by Django 3.2.11 on 2023-12-04 20:09

import bcse_app.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0118_auto_20231204_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vignette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Vignette title', max_length=256)),
                ('blurb', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this vignette', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=bcse_app.models.upload_file_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('featured', models.BooleanField(default=False, help_text='If marked featured, will be displayed on teh Teacher Leadership Opportunity page')),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='responseFile',
            field=models.FileField(blank=True, null=True, upload_to=bcse_app.models.upload_file_to),
        ),
    ]
