# Generated by Django 3.2.11 on 2023-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0119_auto_20231204_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycomponent',
            name='display_other_option',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='surveycomponent',
            name='other_option_label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='vignette',
            name='featured',
            field=models.BooleanField(default=False, help_text='If marked featured, will be displayed on the Teacher Leadership Opportunity page'),
        ),
    ]
