# Generated by Django 3.2.11 on 2023-12-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0120_auto_20231211_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycomponent',
            name='display_other_option',
            field=models.BooleanField(default=False),
        ),
    ]
