# Generated by Django 3.2.11 on 2023-12-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0121_alter_surveycomponent_display_other_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopcategory',
            name='audience',
        ),
    ]
