# Generated by Django 3.2.11 on 2024-01-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0123_auto_20240105_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='admin_notes',
            field=models.CharField(blank=True, help_text='Notes only admins can add/view', max_length=2048, null=True),
        ),
    ]
