# Generated by Django 3.2.11 on 2024-03-15 15:31

import bcse_app.models
import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0126_alter_userprofile_work_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Consumable', max_length=256)),
                ('inventory', ckeditor.fields.RichTextField(blank=True, help_text='Consumable Kit inventory', null=True)),
                ('unit_cost', models.FloatField(blank=True, help_text='Unit cost for the consumable', null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', ckeditor.fields.RichTextField(blank=True, help_text='Inventory notes', null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image that represents this Consumable', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.reservationcolor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
