# Generated by Django 3.2.11 on 2024-03-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0127_consumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='consumables',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='bcse_app.Consumable'),
        ),
    ]
