# Generated by Django 3.2.11 on 2024-06-04 18:41

import bcse_app.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0129_reservation_consumables'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='alumnus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image that represents this Activity Kit', null=True, upload_to=bcse_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='activity',
            name='inventory',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Activity Kit inventory', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kit_name',
            field=models.CharField(help_text='Name of the Activity Kit', max_length=256),
        ),
    ]
