# Generated by Django 3.2.11 on 2024-06-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0130_auto_20240604_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='alumnus',
            new_name='former_member',
        ),
    ]
