# Generated by Django 3.2.11 on 2024-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0131_rename_alumnus_team_former_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='organization',
            field=models.CharField(blank=True, help_text='Org. of the Team Member', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.CharField(blank=True, help_text='Position of the Team Member', max_length=256, null=True),
        ),
    ]
