# Generated by Django 3.2.11 on 2024-07-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0133_reservation_confirmation_email_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcolor',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
