# Generated by Django 3.2.11 on 2024-07-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0134_reservationcolor_low_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='include_gloves_goggles',
            field=models.BooleanField(default=False),
        ),
    ]
