# Generated by Django 3.2.11 on 2024-07-31 18:49

import bcse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0135_reservation_include_gloves_goggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationWorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_to_work_place', to='bcse_app.reservation', unique=True)),
                ('work_place', models.ForeignKey(on_delete=models.SET(bcse_app.models.get_placeholder_workplace), related_name='work_place_to_reservation', to='bcse_app.workplace')),
            ],
        ),
    ]
