# Generated by Django 3.2.11 on 2024-08-01 15:24

import bcse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0136_reservationworkplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_to_work_place', to='bcse_app.registration', unique=True)),
                ('work_place', models.ForeignKey(on_delete=models.SET(bcse_app.models.get_placeholder_workplace), related_name='work_place_to_registration', to='bcse_app.workplace')),
            ],
        ),
    ]
