# Generated by Django 3.2.11 on 2024-08-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0137_registrationworkplace'),
    ]

    operations = [
        migrations.RenameModel('BaxterBoxCategory', 'Tag'),
        migrations.RenameField('BaxterBoxSubCategory', 'category', 'tag'),
        migrations.RenameModel('BaxterBoxSubCategory', 'SubTag'),

    ]
