# Generated by Django 3.2.11 on 2024-08-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0138_auto_20240819_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtag',
            options={'ordering': ['tag__order', 'order']},
        ),
        migrations.AddField(
            model_name='workshop',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', null=True, to='bcse_app.SubTag'),
        ),
        migrations.AlterField(
            model_name='subtag',
            name='name',
            field=models.CharField(help_text='Name of Sub Tag', max_length=256),
        ),
        migrations.AlterField(
            model_name='subtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_tags', to='bcse_app.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Name of the Tag', max_length=256, unique=True),
        ),
    ]
