# Generated by Django 3.2.11 on 2024-08-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0139_auto_20240820_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='vignette',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
