# Generated by Django 3.2.11 on 2024-08-28 14:33

import bcse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0141_alter_vignette_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmissionWorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submission_to_work_place', to='bcse_app.surveysubmission', unique=True)),
                ('work_place', models.ForeignKey(on_delete=models.SET(bcse_app.models.get_placeholder_workplace), related_name='work_place_to_survey_submission', to='bcse_app.workplace')),
            ],
        ),
    ]
