# Generated by Django 3.2.11 on 2024-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0144_auto_20240916_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='credits',
            field=models.CharField(blank=True, help_text='Credits the attendees earn', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='perks',
            field=models.CharField(blank=True, help_text='Workshop perks', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='featured',
            field=models.BooleanField(default=False, help_text='If marked "Featured", this workshop will be displayed under "Past Workshop Examples" tab'),
        ),
    ]
