# Generated by Django 3.2.11 on 2024-10-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0145_auto_20241002_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationworkplace',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_to_work_place', to='bcse_app.reservation'),
        ),
    ]
