# Generated by Django 3.2.11 on 2024-11-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0146_alter_reservationworkplace_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationworkplace',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration_to_work_place', to='bcse_app.registration'),
        ),
    ]
