# Generated by Django 3.2.11 on 2024-11-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0147_alter_registrationworkplace_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysubmissionworkplace',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submission_to_work_place', to='bcse_app.surveysubmission'),
        ),
    ]
