# Generated by Django 3.2.11 on 2024-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0148_alter_surveysubmissionworkplace_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplace',
            name='name',
            field=models.CharField(help_text='Name of Workplace', max_length=256),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='zip_code',
            field=models.CharField(help_text='Zip Code of Workplace', max_length=256),
        ),
    ]
