# Generated by Django 3.2.11 on 2024-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0149_auto_20241119_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationcolor',
            name='description',
            field=models.CharField(help_text='Describe the types of reservations/labs/consumables this color will be applied to', max_length=512),
        ),
        migrations.AlterField(
            model_name='reservationcolor',
            name='target',
            field=models.CharField(choices=[('R', 'Reservation'), ('K', 'Activity and Consumable'), ('B', 'Reservation, Activity and Consumable')], default='R', help_text='The entities this color is applicable to', max_length=1),
        ),
    ]
