# Generated by Django 3.2.11 on 2024-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0150_auto_20241205_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcolor',
            name='low_stock_message',
            field=models.CharField(blank=True, help_text='Message to display to the user when they pick an activity/consumable marked as low stock', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='reservationcolor',
            name='rank',
            field=models.IntegerField(blank=True, help_text='Rank to determine the low stock message to display', null=True),
        ),
    ]
