# Generated by Django 3.2.11 on 2024-12-10 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0151_auto_20241205_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to='bcse_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='reservationcolor',
            name='rank',
            field=models.IntegerField(blank=True, help_text='Rank to determine the low stock message to display', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
