# Generated by Django 3.2.11 on 2024-12-10 15:07

import bcse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0152_auto_20241210_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assignee',
            field=models.ForeignKey(blank=True, default=bcse_app.models.get_placeholder_reservation_assignee, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to='bcse_app.userprofile'),
        ),
    ]
