# Generated by Django 3.2.11 on 2025-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0153_alter_reservation_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='external_link_label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='external_registration_link',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='registration_type',
            field=models.CharField(blank=True, choices=[('R', 'Register'), ('A', 'Apply'), ('E', 'External')], max_length=1, null=True),
        ),
    ]
