# Generated by Django 3.2.11 on 2025-02-27 19:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0154_auto_20250220_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(help_text='Registration statuses this email is sent to', max_length=50)),
                ('email_to', models.CharField(blank=True, help_text='Email addresses separated by commas', max_length=1024, null=True)),
                ('email_subject', models.CharField(max_length=256)),
                ('email_message', ckeditor.fields.RichTextField()),
                ('email_status', models.CharField(choices=[('D', 'Draft'), ('S', 'Sent')], default='D', max_length=1)),
                ('scheduled_date', models.DateField(blank=True, help_text='The date the email is scheduled to be sent', null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_email', to='bcse_app.workshop')),
            ],
            options={
                'ordering': ['modified_date'],
            },
        ),
    ]
