# Generated by Django 3.2.11 on 2025-01-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0155_auto_20241218_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawayrequest',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giveawayrequest',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('P', 'Packed'), ('S', 'Scheduled'), ('D', 'Delivered')], max_length=1, null=True),
        ),
    ]
