# Generated by Django 3.2.11 on 2025-03-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0155_workshopemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopemail',
            name='registration_email_addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='email_to',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by commas', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='registration_status',
            field=models.CharField(help_text='One or more registration statuses this email is sent to', max_length=50),
        ),
    ]
