# Generated by Django 3.2.11 on 2025-03-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0156_auto_20250307_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='featured',
            field=models.BooleanField(default=True, help_text='If marked "Featured", this equipment will be displayed on "The Baxter Box Program" page'),
        ),
    ]
