# Generated by Django 3.2.11 on 2025-04-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0157_equipmenttype_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopemail',
            name='email_bcc',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by commas', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='workshopemail',
            name='email_cc',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by commas', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='registration_status',
            field=models.CharField(help_text='One or more registration statuses this email is sent to. Email will be bccd to these addresses', max_length=50),
        ),
    ]
