# Generated by Django 3.2.11 on 2025-04-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0158_auto_20250403_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopemail',
            name='email_bcc',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by a semicolon', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='email_cc',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by a semicolon', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='email_to',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by a semicolon', max_length=1024, null=True),
        ),
    ]
