# Generated by Django 3.2.11 on 2025-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0159_auto_20250403_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopemail',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='The time the email is scheduled to be sent. If date is set but time is not set, the email will be sent at midnight.', null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='email_bcc',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by a semicolon.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='email_cc',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by a semicolon.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='email_to',
            field=models.CharField(blank=True, help_text='One or more email addresses separated by a semicolon.', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='registration_status',
            field=models.CharField(help_text='One or more registration statuses this email is sent to. Email will be bccd to these addresses.', max_length=50),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='The date the email is scheduled to be sent.', null=True),
        ),
    ]
