# Generated by Django 3.2.11 on 2025-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0160_auto_20250404_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='If marked "Cancelled", registration will be closed and any pre-existing registration data will not be included in the registration report'),
        ),
    ]
