# Generated by Django 3.2.11 on 2025-04-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0161_workshop_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopemail',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='The time the email is scheduled to be sent. If date is set but time is not set, the email will be scheduled for midnight.', null=True),
        ),
    ]
