# Generated by Django 3.2.11 on 2025-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0162_alter_workshopemail_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_notes',
            field=models.CharField(blank=True, help_text='Notes only admins can add/view', max_length=2048, null=True),
        ),
    ]
