# Generated by Django 3.2.11 on 2025-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0163_userprofile_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name_pronounciation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
