# Generated by Django 3.2.11 on 2025-06-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0164_userprofile_name_pronounciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='include_gloves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='include_goggles',
            field=models.BooleanField(default=False),
        ),
    ]
