# Generated by Django 3.2.11 on 2025-07-09 21:01

import bcse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0165_auto_20250623_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='include_gloves_goggles',
        ),
    ]
