# Generated by Django 3.2.11 on 2025-07-09 21:06

import bcse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0166_auto_20250709_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttype',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image at least 400x289 in resolution that represents this equipment category', null=True, upload_to=bcse_app.models.upload_file_to),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(help_text='Name of Equipment Category', max_length=256),
        ),
    ]
