# Generated by Django 3.2.11 on 2025-07-09 21:07

import bcse_app.models
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0167_auto_20250709_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('U', 'Unconfirmed'), ('R', 'Confirmed'), ('O', 'Checked Out'), ('I', 'Checked In'), ('C', 'Completed'), ('N', 'Cancelled')], default='U', max_length=1),
        ),
    ]
