# Generated by Django 3.2.11 on 2025-07-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0168_auto_20250709_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopemail',
            name='photo_release_incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='registration_status',
            field=models.CharField(blank=True, help_text='One or more registration statuses this email is sent to. Email will be bccd to these addresses.', max_length=50, null=True),
        ),
    ]
