# Generated by Django 3.2.11 on 2025-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0169_auto_20250710_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('U', 'Unconfirmed'), ('R', 'Confirmed'), ('O', 'Checked Out'), ('I', 'Completed'), ('N', 'Cancelled')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='workshopemail',
            name='photo_release_incomplete',
            field=models.BooleanField(default=False, help_text='If checked, this email will be sent to users with incomplete photo release within the selected registration status.'),
        ),
    ]
