# Generated by Django 3.2.11 on 2025-07-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0170_auto_20250717_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='resource_url',
            field=models.URLField(blank=True, help_text="URL to a document/artifact/certificate that is downloaded to the user's device once the survey is submitted.", null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('A', 'Async Learning'), ('C', 'Case Study'), ('W', 'Workshop Application/Questionnaire'), ('B', 'Baxter Box Feedback'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preference',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='workshopregistrationsetting',
            name='application',
            field=models.ForeignKey(blank=True, help_text='If selected, users must complete the chosen application or questionnaire before their registration is recorded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_setting', to='bcse_app.survey'),
        ),
    ]
