# Generated by Django 3.2.11 on 2025-09-16 17:25

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0171_auto_20250724_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='workshops', to='bcse_app.Collaborator'),
        ),
        migrations.CreateModel(
            name='WorkshopRegistrationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_status', models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended')], max_length=1)),
                ('email_subject', models.CharField(max_length=256)),
                ('email_message', ckeditor.fields.RichTextField()),
                ('include_calendar_invite', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registration_email', to='bcse_app.workshop')),
            ],
            options={
                'ordering': ['registration_status'],
                'unique_together': {('workshop', 'registration_status')},
            },
        ),
    ]
