# Generated by Django 3.2.11 on 2025-09-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0172_activityinventory_consumableinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='workshops', to='bcse_app.Collaborator'),
        ),
    ]
