# Generated by Django 3.2.11 on 2025-09-16 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0172_auto_20250916_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration_date', models.DateField()),
                ('storage_location', models.CharField(choices=[('RO', 'Room Temp'), ('RE', 'Refrigerator'), ('FR', 'Freezer')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcse_app.consumable')),
            ],
            options={
                'ordering': ['consumable__name', 'storage_location', 'expiration_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('expiration_date', models.DateField()),
                ('storage_location', models.CharField(choices=[('RO', 'Room Temp'), ('RE', 'Refrigerator'), ('FR', 'Freezer')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcse_app.activity')),
            ],
            options={
                'ordering': ['activity__name', 'storage_location', 'expiration_date'],
            },
        ),
    ]
