# Generated by Django 3.2.11 on 2025-09-17 15:38

import bcse_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0173_activityinventory_consumableinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pickup_assignee',
            field=models.ForeignKey(blank=True, default=bcse_app.models.get_placeholder_reservation_assignee, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_assigned_reservations', to='bcse_app.userprofile'),
        ),
    ]
