# Generated by Django 3.2.11 on 2025-10-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0174_reservation_pickup_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='admin_notification',
            field=models.BooleanField(default=False, help_text='Send email notification to admins when a survey is submitted.'),
        ),
    ]
