# Generated by Django 3.2.11 on 2025-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0175_survey_admin_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinventory',
            name='notes',
            field=models.CharField(blank=True, help_text='Any additional information', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='consumableinventory',
            name='notes',
            field=models.CharField(blank=True, help_text='Any additional information', max_length=2048, null=True),
        ),
    ]
