# Generated by Django 3.2.11 on 2025-10-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0176_auto_20251021_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='admin_notes',
            field=models.CharField(blank=True, help_text='Notes only admins can add/view', max_length=2048, null=True),
        ),
    ]
