# Generated by Django 3.2.11 on 2025-10-23 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0177_workplace_admin_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationcolor',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='reservationcolor',
            name='order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
