# Generated by Django 5.2.7 on 2025-12-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0178_auto_20251023_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumableinventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
