# Generated by Django 3.2.11 on 2025-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0178_auto_20251023_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
