# Generated by Django 5.2.7 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0179_alter_activityinventory_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Secondary email can be used to Sign In.  Any email sent to the primary email will also be sent to the secondary email.', max_length=256, null=True),
        ),
    ]
