# Generated by Django 5.2.7 on 2025-12-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0179_userprofile_secondary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumableinventory',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_email',
            field=models.EmailField(blank=True, help_text='Secondary email can be used to Sign In.  Any email sent to the primary email will also be sent to the secondary email.', max_length=256, null=True),
        ),
    ]
