# Generated by Django 5.2.7 on 2025-12-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0180_userprofile_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherleader',
            name='bcse_role',
            field=models.CharField(choices=[('T', 'Teacher Leader'), ('F', 'Other Facilitator')], default='T', max_length=1),
        ),
    ]
