# Generated by Django 5.2.7 on 2025-12-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0181_teacherleader_bcse_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
