# Generated by Django 5.2.7 on 2025-12-22 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0182_collaborator_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='end_time',
            field=models.TimeField(default=datetime.time(17, 0), help_text='Workshop end time'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Workshop start time'),
        ),
    ]
