# Generated by Django 5.2.7 on 2026-01-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0183_alter_workshop_end_time_alter_workshop_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='sub_status',
            field=models.CharField(choices=[('P', 'Participant'), ('F', 'Facilitator/Presenter'), ('S', 'Staff/Volunteer'), ('O', 'Observer')], default='P', max_length=1),
        ),
    ]
