# Generated by Django 5.2.7 on 2026-01-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0184_registration_sub_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended'), ('U', 'No-show')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='registrationemailmessage',
            name='registration_status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended'), ('U', 'No-show')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='workshopregistrationemail',
            name='registration_status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended'), ('U', 'No-show')], max_length=1),
        ),
    ]
