# Generated by Django 5.2.7 on 2026-01-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0185_alter_registration_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopemail',
            name='registration_sub_status',
            field=models.CharField(blank=True, help_text='One or more registration sub statuses this email is sent to. Email will be bccd to these addresses.', max_length=50, null=True),
        ),
    ]
