# Generated by Django 5.2.7 on 2026-01-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0187_alter_registration_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='term_id',
        ),
    ]
