# Generated by Django 5.2.7 on 2026-01-27 14:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0188_remove_workplace_term_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Notes', null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Notes', null=True),
        ),
    ]
