# Generated by Django 5.2.7 on 2026-02-11 23:20

import bcse_app.models
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0189_remove_activity_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Giveaway', max_length=256)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this Giveaway', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('max_quantity_allowed', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('on_hold_quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('given_quantity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GiveawayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied'), ('C', 'Cancelled')], default='P', max_length=1)),
                ('delivery_status', models.CharField(blank=True, choices=[('P', 'Packed'), ('S', 'Scheduled'), ('D', 'Delivered')], max_length=1, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_detail', to='bcse_app.giveaway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_giveaway_request', to='bcse_app.userprofile')),
                ('work_place', models.ForeignKey(on_delete=models.SET(bcse_app.models.get_placeholder_workplace), related_name='work_place_to_giveaway_request', to='bcse_app.workplace')),
            ],
            options={
                'ordering': ['created_date', 'user__user__last_name'],
            },
        ),
    ]
