# Generated by Django 5.2.7 on 2026-01-28 20:03

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0189_remove_activity_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDeliveryPickupEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_or_pickup', models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], max_length=1, unique=True)),
                ('email_subject', models.CharField(max_length=256)),
                ('email_message', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDeliveryPickupEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_or_pickup', models.CharField(choices=[('D', 'Delivery'), ('P', 'Pickup')], max_length=1)),
                ('email_subject', models.CharField(blank=True, help_text='Email subject added here will override the email subject from the template for this reservation.', max_length=256, null=True)),
                ('email_message', ckeditor.fields.RichTextField(blank=True, help_text='Email message added here will be appended to the email message from the template for this reservation.', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_emails', to='bcse_app.reservation')),
            ],
            options={
                'unique_together': {('reservation', 'delivery_or_pickup')},
            },
        ),
    ]
