# Generated by Django 5.2.7 on 2026-01-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0190_reservationdeliverypickupemailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('A', 'BCSE Admin'), ('T', 'K-12 Teacher or Administrator'), ('P', 'Other Professional'), ('S', 'BCSE Staff'), ('D', 'Box Driver')], max_length=1),
        ),
    ]
