# Generated by Django 5.2.7 on 2026-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0191_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='consumables',
            field=models.ManyToManyField(blank=True, help_text='Scroll down for more consumable options', null=True, to='bcse_app.consumable'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='equipment_mapping',
            field=models.ManyToManyField(blank=True, help_text='Scroll down for more equipment options', null=True, to='bcse_app.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Scroll down for more tag options', null=True, to='bcse_app.subtag'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Scroll down for more tag options', null=True, to='bcse_app.subtag'),
        ),
    ]
