# Generated by Django 5.2.7 on 2026-02-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0192_alter_activity_consumables_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceLowIncomeStudentPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField(choices=[(2009, '2009-2010'), (2010, '2010-2011'), (2011, '2011-2012'), (2012, '2012-2013'), (2013, '2013-2014'), (2014, '2014-2015'), (2015, '2015-2016'), (2016, '2016-2017'), (2017, '2017-2018'), (2018, '2018-2019'), (2019, '2019-2020'), (2020, '2020-2021'), (2021, '2021-2022'), (2022, '2022-2023'), (2023, '2023-2024'), (2024, '2024-2025'), (2025, '2025-2026'), (2026, '2026-2027'), (2027, '2027-2028'), (2028, '2028-2029'), (2029, '2029-2030'), (2030, '2030-2031')])),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcse_app.workplace')),
            ],
            options={
                'unique_together': {('workplace', 'start_year')},
            },
        ),
    ]
