# Generated by Django 5.2.7 on 2026-02-20 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0193_workplacelowincomestudentpercentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workplacelowincomestudentpercentage',
            options={'ordering': ['workplace', 'start_year']},
        ),
        migrations.AlterField(
            model_name='workplacelowincomestudentpercentage',
            name='workplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_income_student_percentage', to='bcse_app.workplace'),
        ),
    ]
