# Generated by Django 5.2.7 on 2026-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0194_alter_workplacelowincomestudentpercentage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('target_url', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_protected', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
