# Generated by Django 5.2.7 on 2026-03-10 14:36

import bcse_app.models
import django.db.models.deletion
from django.db import migrations, models


def set_default_sub_status(apps, schema_editor):
    Reservation = apps.get_model('bcse_app', 'Reservation')
    SubStatus = apps.get_model('bcse_app', 'ReservationColor')
    default_sub_status = SubStatus.objects.filter(order=1, target='R').first()
    Reservation.objects.filter(status='U').update(color=default_sub_status)

class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0195_urlmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='color',
            field=models.ForeignKey(blank=True, default=bcse_app.models.get_default_reservation_sub_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcse_app.reservationcolor'),
        ),
        migrations.RunPython(set_default_sub_status),
    ]
