# Generated by Django 5.2.7 on 2026-03-24 12:01

import bcse_app.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0196_alter_reservation_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Section Title.', max_length=256)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('display_setting', models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1)),
                ('survey_button_label', models.CharField(blank=True, help_text='Survey Button Label. Defaults to the survey name.', max_length=256, null=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image for this section', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('image_position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='L', max_length=1)),
                ('button_label', models.CharField(blank=True, max_length=256, null=True)),
                ('button_url', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.IntegerField()),
                ('display_line_break', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload an image from the Workshop', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('order', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('F', 'Facilitator/Presenter'), ('S', 'Staff/Volunteer'), ('O', 'Collaborator/Partner/Observer')], max_length=1)),
                ('vip', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role', '-created_date'],
            },
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='nid',
        ),
        migrations.AddField(
            model_name='workshop',
            name='display_general_information',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='gallery_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshop',
            name='gallery_title',
            field=models.CharField(blank=True, help_text='Gallery Title.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopcategory',
            name='is_super',
            field=models.BooleanField(default=False, help_text='Super workshops get extra fields to store evergreen language, save the date, call for presenters, faq content'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='sub_status',
            field=models.CharField(choices=[('P', 'Participant'), ('F', 'Facilitator/Presenter'), ('S', 'Staff/Volunteer'), ('O', 'Collaborator/Partner/Observer')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('A', 'Async Learning'), ('C', 'Case Study'), ('W', 'Workshop Application/Questionnaire'), ('P', 'Workshop Survey'), ('B', 'Baxter Box Feedback'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='bcse_app.collaborator'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='On Windows use Ctrl+Click to make multiple selection.  On a Mac use Cmd+Click to make multiple selection', to='bcse_app.subtag'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='teacher_leaders',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='bcse_app.teacherleader'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['workshop_category'], name='idx_workshop_category'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['start_date'], name='idx_start_date'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['end_date'], name='idx_end_date'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['cancelled'], name='idx_cancelled'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddIndex(
            model_name='workshop',
            index=models.Index(fields=['start_date', 'end_date'], name='idx_start_end_date'),
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_detail', to='bcse_app.survey'),
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_detail', to='bcse_app.workshop'),
        ),
        migrations.AddField(
            model_name='workshopimage',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_image', to='bcse_app.workshop'),
        ),
        migrations.AddField(
            model_name='workshopinvitee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_workshops', to='bcse_app.userprofile'),
        ),
        migrations.AddField(
            model_name='workshopinvitee',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invitees', to='bcse_app.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopinvitee',
            unique_together={('workshop', 'user')},
        ),
    ]
