# Generated by Django 5.2.7 on 2026-03-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0197_super_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accessibility_notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
