# Generated by Django 5.2.7 on 2026-03-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0197_workshopdetails_workshopimage_workshopinvitee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_call_for_presenters',
        ),
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_evergreen_language',
        ),
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_faq',
        ),
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_image_gallery',
        ),
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_logistics',
        ),
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_save_the_date',
        ),
        migrations.RemoveField(
            model_name='workshopdetails',
            name='display_thank_you_and_recap',
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='call_for_presenters_button_label',
            field=models.CharField(blank=True, help_text='Enter Call For Presenters Button Label. Defaults to the survey name.', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='call_for_presenters_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='call_for_presenters_title',
            field=models.CharField(blank=True, help_text='Enter Call For Presenters Section Title. Defaults to "Call For Presenters".', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='evergreen_language_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='evergreen_language_title',
            field=models.CharField(blank=True, help_text='Enter Evergreen Language Section Title. Defaults to "Evergreen Language".', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='faq_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='faq_title',
            field=models.CharField(blank=True, help_text='FAQ', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='image_gallery_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='image_gallery_title',
            field=models.CharField(blank=True, help_text='Enter Image Gallery Section Title. Defaults to "Image Gallery"', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='logistics_information_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='logistics_information_title',
            field=models.CharField(blank=True, help_text='Enter Logistics Information Section Title. Defaults to "Logistics Information".', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='save_the_date_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='save_the_date_title',
            field=models.CharField(blank=True, help_text='Enter Save The Date Section Title. Defaults to "Save The Date".', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='thank_you_and_recap_display_setting',
            field=models.CharField(choices=[('H', 'Hide'), ('P', 'Public'), ('L', 'Logged in User'), ('R', 'Registered User')], default='H', max_length=1),
        ),
        migrations.AddField(
            model_name='workshopdetails',
            name='thank_you_and_recap_title',
            field=models.CharField(blank=True, help_text='Enter Thank You and Recap Section Title. Defaults to "Thank You and Recap"', max_length=256, null=True),
        ),
    ]
