# Generated by Django 5.2.7 on 2026-04-01 17:54

import bcse_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0198_userprofile_accessibility_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=bcse_app.models.upload_file_to)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('workshop_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bcse_app.workshopemail')),
            ],
        ),
    ]
