# Generated by Django 5.2.7 on 2026-04-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0199_workshop_email_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdetail',
            name='button_target',
            field=models.CharField(choices=[('_self', 'Same Window (_self)'), ('_blank', 'New Window (_blank)')], default='_self', max_length=10),
        ),
        migrations.AddField(
            model_name='workshopdetail',
            name='survey_target',
            field=models.CharField(choices=[('_self', 'Same Window (_self)'), ('_blank', 'New Window (_blank)')], default='_self', max_length=10),
        ),
    ]
