# Generated by Django 5.2.7 on 2026-04-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0200_workshopdetail_button_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='admin_notes',
            field=models.CharField(blank=True, help_text='Notes only admins can add/view', max_length=2048, null=True),
        ),
    ]
