# Generated by Django 5.2.7 on 2026-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0201_registration_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopimage',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
