# Generated by Django 5.2.7 on 2026-04-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0202_workshopimage_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='county',
            field=models.CharField(choices=[('C', 'Cook'), ('L', 'Lake'), ('O', 'Other')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workplace',
            name='other_county',
            field=models.CharField(blank=True, help_text='County not on the list', max_length=256, null=True),
        ),
    ]
