# Generated by Django 5.2.7 on 2026-04-16 18:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0203_workplace_county_workplace_other_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='grades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('E', 'Grades K-5'), ('M', 'Grades 6-8'), ('H', 'Grades 9-12'), ('C', 'Above Grade 12')], max_length=1), blank=True, default=list, size=None),
        ),
    ]
