# Generated by Django 5.2.7 on 2026-04-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0204_workplace_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='user_notes',
            field=models.CharField(blank=True, help_text='Anything about this workplace not captured by the other fields', max_length=2048, null=True),
        ),
    ]
