# Generated by Django 5.2.7 on 2026-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0205_workplace_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='other_category',
            field=models.CharField(blank=True, help_text='Other category not in the list', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('is_other', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_other', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_other', True)), fields=('is_other',), name='only_one_is_other_instance')],
            },
        ),
        migrations.AddField(
            model_name='workplace',
            name='school_categories',
            field=models.ManyToManyField(blank=True, related_name='schools', to='bcse_app.schoolcategory'),
        ),
    ]
