# Generated by Django 5.2.7 on 2026-04-22 14:18

import bcse_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0206_workplace_other_category_schoolcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistrationsetting',
            name='email_banner',
            field=models.ImageField(blank=True, help_text='Upload an image that will be used as an email banner in ad-hoc and automated emails', null=True, upload_to=bcse_app.models.upload_file_to),
        ),
    ]
