# Generated by Django 5.2.7 on 2026-04-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0207_workshopregistrationsetting_email_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopemail',
            name='invitee_email_addresses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshopemail',
            name='invitee_role',
            field=models.CharField(blank=True, help_text='One or more invitee role this email is sent to. Email will be sent to these addresses individually.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workshopemail',
            name='vip_invitee',
            field=models.BooleanField(default=False, help_text='If checked, this email will be sent to VIP invitees within the selected invitee role.'),
        ),
    ]
