# Generated by Django 5.2.7 on 2026-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0208_workshopemail_invitee_email_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='feedback_status',
            field=models.CharField(choices=[('N', 'Email Not Sent'), ('E', 'Email Sent'), ('I', 'Feedback In Progress'), ('S', 'Feedback Submitted'), ('A', 'Feedback Submitted By Admin')], default='N', max_length=1),
        ),
    ]
