# Generated by Django 5.2.7 on 2026-06-26 01:01

import bcse_app.models
import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0209_alter_reservation_feedback_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_timeslots', to='bcse_app.workshop')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='BreakoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, help_text='Upload an image that represents this session.', null=True, upload_to=bcse_app.models.upload_file_to)),
                ('location', models.CharField(max_length=256)),
                ('resources', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('facilitators', models.ManyToManyField(blank=True, null=True, to='bcse_app.teacherleader')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslot_breakout_sessions', to='bcse_app.timeslot')),
            ],
            options={
                'ordering': ['timeslot__start_time'],
            },
        ),
    ]
