# Generated by Django 5.2.7 on 2026-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0209_alter_reservation_feedback_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='rcdts_code',
            field=models.CharField(blank=True, help_text='RCDTS Code from Illinois State Board Of Education', max_length=256, null=True),
        ),
    ]
