# Generated by Django 5.2.7 on 2026-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0210_workplace_rcdts_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationemailmessage',
            options={'ordering': ['registration_status_from', 'registration_status']},
        ),
        migrations.AlterModelOptions(
            name='workshopregistrationemail',
            options={'ordering': ['registration_status_from', 'registration_status']},
        ),
        migrations.AlterUniqueTogether(
            name='workshopregistrationemail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='registrationemailmessage',
            name='registration_status_from',
            field=models.CharField(blank=True, choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended'), ('U', 'Did Not Attend')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='workshopregistrationemail',
            name='registration_status_from',
            field=models.CharField(blank=True, choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended'), ('U', 'Did Not Attend')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrationemailmessage',
            name='registration_status',
            field=models.CharField(choices=[('R', 'Registered'), ('A', 'Applied'), ('C', 'Accepted'), ('D', 'Denied'), ('N', 'Cancelled'), ('W', 'Waitlisted'), ('P', 'Pending'), ('T', 'Attended'), ('U', 'Did Not Attend')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='registrationemailmessage',
            unique_together={('registration_status_from', 'registration_status')},
        ),
        migrations.AlterUniqueTogether(
            name='workshopregistrationemail',
            unique_together={('workshop', 'registration_status_from', 'registration_status')},
        ),
    ]
