# Generated by Django 5.2.7 on 2026-07-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0210_timeslot_breakoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakoutsession',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, to='bcse_app.collaborator'),
        ),
    ]
