# Generated by Django 5.2.7 on 2026-07-08 13:28

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_grades(apps, schema_editor):

    MyModel = apps.get_model("bcse_app", "UserProfile")

    for obj in MyModel.objects.all().iterator():
        if obj.grades_taught:
            if obj.grades_taught == 'H':
                obj.grades = ['F', 'S', 'J', 'N']
            else:
                obj.grades = [obj.grades_taught]
        else:
            obj.grades = []
        obj.save(update_fields=["grades"])


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0211_alter_registrationemailmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('E', 'Elementary School'), ('M', 'Middle School'), ('F', 'Freshman'), ('S', 'Sophomores'), ('J', 'Juniors'), ('N', 'Seniors'), ('O', 'Out-of-school Time'), ('P', 'Post-Secondary'), ('I', 'Informal')], max_length=1), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grades_taught',
            field=models.CharField(blank=True, choices=[('E', 'Elementary School'), ('M', 'Middle School'), ('H', 'High School'), ('F', 'Freshman'), ('S', 'Sophomores'), ('J', 'Juniors'), ('N', 'Seniors'), ('O', 'Out-of-school Time'), ('P', 'Post-Secondary'), ('I', 'Informal')], max_length=1, null=True),
        ),
        migrations.RunPython(
            migrate_grades,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="grades_taught",
        ),
    ]
