# Generated by Django 5.2.7 on 2026-07-08 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0212_userprofile_grades_alter_userprofile_grades_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GS', 'General Science'), ('BI', 'Biology'), ('AB', 'AP Biology '), ('DB', 'Dual Credit Biology'), ('IB', 'IB Biology'), ('CH', 'Chemistry'), ('PH', 'Physics'), ('BT', 'Biotech'), ('AP', 'Anatomy and Physiology'), ('EO', 'Electives/Other')], max_length=2), blank=True, default=list, size=None),
        ),
    ]
