# Generated by Django 5.2.7 on 2026-08-11 16:55

import bcse_app.models
import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0214_timeslot_breakoutsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user',
                'verbose_name_plural': 'historical users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUserProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('secondary_email', models.EmailField(blank=True, help_text='Secondary email can be used to Sign In.  Any email sent to the primary email will also be sent to the secondary email.', max_length=256, null=True)),
                ('user_role', models.CharField(choices=[('A', 'BCSE Admin'), ('T', 'K-12 Teacher or Administrator'), ('P', 'Other Professional'), ('S', 'BCSE Staff'), ('D', 'Box Driver')], max_length=1)),
                ('image', models.TextField(blank=True, help_text='Profile image', max_length=100, null=True)),
                ('validation_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('iein', models.CharField(blank=True, max_length=20, null=True)),
                ('grades', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('E', 'Elementary School'), ('M', 'Middle School'), ('F', 'Freshman'), ('S', 'Sophomores'), ('J', 'Juniors'), ('N', 'Seniors'), ('O', 'Out-of-school Time'), ('P', 'Post-Secondary'), ('I', 'Informal')], max_length=1), blank=True, default=list, size=None)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('GS', 'General Science'), ('BI', 'Biology'), ('AB', 'AP Biology '), ('DB', 'Dual Credit Biology'), ('IB', 'IB Biology'), ('CH', 'Chemistry'), ('PH', 'Physics'), ('BT', 'Biotech'), ('AP', 'Anatomy and Physiology'), ('EO', 'Electives/Other')], max_length=2), blank=True, default=list, size=None)),
                ('other_subject', models.CharField(blank=True, max_length=20, null=True)),
                ('subscribe', models.BooleanField(default=False)),
                ('photo_release_complete', models.BooleanField(default=False)),
                ('dietary_preference', models.CharField(blank=True, max_length=256, null=True)),
                ('admin_notes', models.CharField(blank=True, help_text='Notes only admins can add/view', max_length=2048, null=True)),
                ('name_pronounciation', models.CharField(blank=True, max_length=256, null=True)),
                ('accessibility_notes', models.CharField(blank=True, max_length=256, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_place', models.ForeignKey(blank=True, db_constraint=False, default=bcse_app.models.get_placeholder_workplace, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bcse_app.workplace')),
            ],
            options={
                'verbose_name': 'historical user profile',
                'verbose_name_plural': 'historical user profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
