# Generated by Django 5.2.7 on 2026-08-11 16:57

from django.db import migrations
from django.core.management import call_command


def populate_history(apps, schema_editor):
    call_command("populate_history", "--auto")

class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0215_historicaluser_historicaluserprofile'),
    ]

    operations = [
        migrations.RunPython(populate_history),
    ]
