# Generated by Django 5.2.7 on 2026-09-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcse_app', '0216_initial_historical_user_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['path'], name='bcse_app_pa_path_12758f_idx'), models.Index(fields=['created_date'], name='bcse_app_pa_created_abfbd9_idx'), models.Index(fields=['user', 'created_date'], name='bcse_app_pa_user_id_7d7c7e_idx')],
            },
        ),
    ]
