from django.urls import path

from . import views

app_name = 'bcse'

urlpatterns = [
    path('', views.home, name='home'),
    path('reservation/<int:id>/edit', views.reservationEdit, name='reservationEdit'),
    path('reservation/<int:id>/view', views.reservationView, name='reservationView'),
    path('reservation/<int:id>/delete', views.reservationDelete, name='reservationDelete'),
    path('reservation/<int:id>/cancel', views.reservationCancel, name='reservationCancel'),
    path('reservation/<int:id>/message', views.reservationMessage, name='reservationMessage'),
    path('reservation/<int:id>/dismissMessages', views.reservationMessageDismiss, name='reservationMessageDismiss'),
    path('reservation/<int:id>/sendconfirmationemail', views.reservationConfirmationEmailSend, name='reservationConfirmationEmailSend'),
    path('reservation/<int:id>/sendfeedbackemail', views.reservationFeedbackEmailSend, name='reservationFeedbackEmailSend'),
    path('reservation/<int:id>/workplace', views.reservationWorkPlaceEdit, name='reservationWorkPlaceEdit'),
    path('reservation/<int:id>/viewconfirmationemail', views.reservationConfirmationEmailView, name='reservationConfirmationEmailView'),
    path('reservation/new', views.reservationEdit, name='reservationNew'),
    path('reservations', views.reservations, name='reservations'),
    path('reservations/search/<str:display>', views.reservationsSearch, name='reservationsSearch'),
    path('reservations/search/', views.reservationsSearch, name='reservationsSearch'),
    path('reservations/dismissMessages', views.reservationMessageDismiss, name='reservationMessageDismiss'),
    path('reservation/<int:reservation_id>/deliveryAddress/edit', views.reservationDeliveryAddressEdit, name='reservationDeliveryAddressEdit'),
    path('reservation/<int:reservation_id>/deliveryAddress/delete', views.reservationDeliveryAddressDelete, name='reservationDeliveryAddressDelete'),
    path('reservation/<int:reservation_id>/update', views.reservationUpdate, name='reservationUpdate'),
    path('availability/<int:id>', views.getAvailabilityData, name='getAvailabilityData'),
    path('availability/new', views.getAvailabilityData, name='getAvailabilityData'),
    path('workshop/<int:id>/edit', views.workshopEdit, name='workshopEdit'),
    path('workshop/new', views.workshopEdit, name='workshopNew'),
    path('workshop/<int:id>/view', views.workshopView, name='workshopView'),
    path('workshop/<int:id>/copy', views.workshopCopy, name='workshopCopy'),
    path('workshop/<int:id>/delete', views.workshopDelete, name='workshopDelete'),
    path('workshop/<int:id>/registration_setting/edit', views.workshopRegistrationSetting, name='workshopRegistrationSetting'),
    path('workshop/<int:id>/registrants/', views.workshopRegistrants, name='workshopRegistrants'),
    path('workshop/<int:id>/registrants/search', views.workshopRegistrantsSearch, name='workshopRegistrantsSearch'),
    path('workshop/<int:id>/registrants/upload', views.workshopRegistrantsUpload, name='workshopRegistrantsUpload'),
    path('adminConfiguration/workshops/upload', views.workshopsUpload, name='workshopsUpload'),
    path('adminConfiguration/workshops/registrants/upload', views.allWorkshopsRegistrantsUpload, name='allWorkshopsRegistrantsUpload'),
    path('workshop/<int:workshop_id>/registration/', views.workshopRegistration, name='workshopRegistration'),
    path('workshop/<int:workshop_id>/registration/<int:id>/edit', views.workshopRegistrationEdit, name='workshopRegistrationEdit'),
    path('workshop/<int:workshop_id>/registration/<int:id>/delete', views.workshopRegistrationDelete, name='workshopRegistrationDelete'),
    path('workshop/<int:workshop_id>/registration/<int:id>/cancel', views.workshopRegistrationCancel, name='workshopRegistrationCancel'),
    path('workshop/<int:workshop_id>/registration/questionnaire', views.workshopRegistrationQuestionnaire, name='workshopRegistrationQuestionnaire'),

    path('workshop/<int:workshop_id>/emails', views.workshopEmails, name='workshopEmails'),
    path('workshop/<int:workshop_id>/email/<int:id>/edit', views.workshopEmailEdit, name='workshopEmailEdit'),
    path('workshop/<int:workshop_id>/email/new', views.workshopEmailEdit, name='workshopEmailNew'),
    path('workshop/<int:workshop_id>/email/<int:id>/delete', views.workshopEmailDelete, name='workshopEmailDelete'),

    path('workshop/<int:workshop_id>/registration_emails', views.workshopRegistrationEmails, name='workshopRegistrationEmails'),
    path('workshop/<int:workshop_id>/registration_emails/<int:id>/edit', views.workshopRegistrationEmailEdit, name='workshopRegistrationEmailEdit'),
    path('workshop/<int:workshop_id>/registration_emails/new', views.workshopRegistrationEmailEdit, name='workshopRegistrationEmailNew'),
    path('workshop/<int:workshop_id>/registration_emails/<int:id>/delete', views.workshopRegistrationEmailDelete, name='workshopRegistrationEmailDelete'),
    path('workshop/<int:workshop_id>/registration_emails/<int:id>/preview', views.workshopRegistrationEmailPreview, name='workshopRegistrationEmailPreview'),

    path('workshop/<int:workshop_id>/email/<int:id>/preview', views.workshopEmailPreview, name='workshopEmailPreview'),
    path('workshop/<int:workshop_id>/email/<int:id>/send', views.workshopEmailSend, name='workshopEmailSend'),
    path('workshop/<int:workshop_id>/email/<int:id>/copy', views.workshopEmailCopy, name='workshopEmailCopy'),

    path('workshops/search/<str:display>/<str:period>/', views.workshopsSearch, name='workshopsSearch'),
    path('workshops/search/<str:display>/<str:period>/<str:extra>/', views.workshopsSearch, name='workshopsSearchExtra'),
    path('workshops/<str:display>/<str:period>/', views.workshops, name='workshops'),
    path('workshops/<str:display>/<str:period>/<str:extra>/', views.workshops, name='workshopsExtra'),

    path('signin/', views.userSignin, name='signin'),
    path('signin_redirect/', views.signinRedirect, name='signinRedirect'),
    path('signin/<str:user_email>/', views.userSignin, name='signin'),
    path('signup/', views.userSignup, name='signup'),
    path('signout/', views.userSignout, name='signout'),
    path('userProfile/<int:id>/edit', views.userProfileEdit, name='userProfileEdit'),
    path('userProfile/<int:id>/view', views.userProfileView, name='userProfileView'),
    path('userProfile/<int:id>/delete', views.userProfileDelete, name='userProfileDelete'),
    path('userProfile/<int:id>/workplace', views.userProfileWorkPlace, name='userProfileWorkPlace'),
    path('adminConfiguration/', views.adminConfiguration, name='adminConfiguration'),
    path('adminConfiguration/baxter_box/activity/<int:id>/edit', views.activityEdit, name='activityEdit'),
    path('adminConfiguration/baxter_box/activity/<int:id>/update', views.activityUpdate, name='activityUpdate'),
    path('adminConfiguration/baxter_box/activity/<int:id>/reservation/<int:reservation_id>/update', views.activityUpdate, name='reservationActivityUpdate'),
    path('adminConfiguration/baxter_box/activity/<int:id>/delete', views.activityDelete, name='activityDelete'),
    path('adminConfiguration/baxter_box/activity/new', views.activityEdit, name='activityNew'),
    path('adminConfiguration/baxter_box/activities/', views.activities, name='activities'),
    path('activity/<int:id>/view', views.activityView, name='activityView'),

    path('adminConfiguration/baxter_box/consumable/<int:id>/edit', views.consumableEdit, name='consumableEdit'),
    path('adminConfiguration/baxter_box/consumable/<int:id>/update', views.consumableUpdate, name='consumableUpdate'),
    path('adminConfiguration/baxter_box/consumable/<int:id>/delete', views.consumableDelete, name='consumableDelete'),
    path('adminConfiguration/baxter_box/consumable/new', views.consumableEdit, name='consumableNew'),
    path('adminConfiguration/baxter_box/consumables/', views.consumables, name='consumables'),

    path('adminConfiguration/equipmentType/<int:id>/edit', views.equipmentTypeEdit, name='equipmentTypeEdit'),
    path('adminConfiguration/equipmentType/<int:id>/delete', views.equipmentTypeDelete, name='equipmentTypeDelete'),
    path('adminConfiguration/equipmentType/new', views.equipmentTypeEdit, name='equipmentTypeNew'),
    path('adminConfiguration/equipmentTypes/', views.equipmentTypes, name='equipmentTypes'),
    path('adminConfiguration/availabilityCalendar/', views.adminAvailabilityCalendar, name='adminAvailabilityCalendar'),
    path('adminConfiguration/reservationCalendar/', views.adminReservationCalendar, name='adminReservationCalendar'),
    path('adminConfiguration/reservationCalendar/update', views.adminReservationCalendarUpdate, name='adminReservationCalendarUpdate'),

    path('equipmentType/<int:id>/view', views.equipmentTypeView, name='equipmentTypeView'),
    path('adminConfiguration/equipment/<int:id>/edit', views.equipmentEdit, name='equipmentEdit'),
    path('adminConfiguration/equipment/<int:id>/delete', views.equipmentDelete, name='equipmentDelete'),
    path('adminConfiguration/equipment/<int:id>/overbooking/<int:reservation_id>', views.equipmentOverbookedReservations, name='equipmentOverbookedReservations'),
    path('adminConfiguration/equipment/new', views.equipmentEdit, name='equipmentNew'),
    path('adminConfiguration/equipments/', views.equipments, name='equipments'),

    path('adminConfiguration/baxter_box/usage_report/', views.baxterBoxUsageReport, name='baxterBoxUsageReport'),
    path('adminConfiguration/baxter_box/usage_report/search', views.baxterBoxUsageReportSearch, name='baxterBoxUsageReportSearch'),
    path('adminConfiguration/baxter_box/blackout_date/<int:id>/edit', views.blackoutDateEdit, name='blackoutDateEdit'),
    path('adminConfiguration/baxter_box/blackout_date/new', views.blackoutDateEdit, name='blackoutDateNew'),
    path('adminConfiguration/baxter_box/blackout_date/<int:id>/delete', views.blackoutDateDelete, name='blackoutDateDelete'),
    path('adminConfiguration/baxter_box/settings/', views.baxterBoxSettings, name='baxterBoxSettings'),
    path('adminConfiguration/baxter_box/message/<int:id>/edit', views.baxterBoxMessageEdit, name='baxterBoxMessageEdit'),
    path('adminConfiguration/baxter_box/message/new', views.baxterBoxMessageEdit, name='baxterBoxMessageNew'),

    path('adminConfiguration/baxter_box/message/<int:id>/delete', views.baxterBoxMessageDelete, name='baxterBoxMessageDelete'),
    path('adminConfiguration/tags/', views.tags, name='tags'),
    path('adminConfiguration/subTags/', views.subTags, name='subTags'),
    path('adminConfiguration/tag/<int:id>/edit', views.tagEdit, name='tagEdit'),
    path('adminConfiguration/tag/<int:id>/delete', views.tagDelete, name='tagDelete'),
    path('adminConfiguration/tag/new', views.tagEdit, name='tagNew'),
    path('adminConfiguration/subTag/<int:id>/edit', views.subTagEdit, name='subTagEdit'),
    path('adminConfiguration/subTag/<int:id>/delete', views.subTagDelete, name='subTagDelete'),
    path('adminConfiguration/subTag/new', views.subTagEdit, name='subTagNew'),

    path('adminConfiguration/baxter_box/reservation_color/<int:id>/edit', views.reservationColorEdit, name='reservationColorEdit'),
    path('adminConfiguration/baxter_box/reservation_color/new', views.reservationColorEdit, name='reservationColorNew'),
    path('adminConfiguration/baxter_box/reservation_color/<int:id>/delete', views.reservationColorDelete, name='reservationColorDelete'),
    path('adminConfiguration/baxter_box/reservation_colors/', views.reservationColors, name='reservationColors'),

    path('adminConfiguration/baxter_box/inventory/', views.baxterBoxInventory, name='baxterBoxInventory'),
    path('adminConfiguration/baxter_box/inventory/search', views.baxterBoxInventorySearch, name='baxterBoxInventorySearch'),
    path('adminConfiguration/baxter_box/inventory/create', views.inventoryCreate, name='inventoryCreate'),
    path('adminConfiguration/baxter_box/inventory/<int:id>/<str:inventory_type>/edit', views.inventoryEdit, name='inventoryEdit'),
    path('adminConfiguration/baxter_box/inventory/<str:inventory_type>/new', views.inventoryEdit, name='inventoryNew'),
    path('adminConfiguration/baxter_box/inventory/<int:id>/<str:inventory_type>/delete', views.inventoryDelete, name='inventoryDelete'),

    path('adminConfiguration/workshopCategory/<int:id>/edit', views.workshopCategoryEdit, name='workshopCategoryEdit'),
    path('adminConfiguration/workshopCategory/<int:id>/delete', views.workshopCategoryDelete, name='workshopCategoryDelete'),
    path('adminConfiguration/workshopCategory/<int:id>/details', views.getWorkshopCategoryDetails, name='getWorkshopCategoryDetails'),
    path('adminConfiguration/workshopCategory/new', views.workshopCategoryEdit, name='workshopCategoryNew'),
    path('adminConfiguration/workshopCategories/', views.workshopCategories, name='workshopCategories'),
    path('adminConfiguration/workshopCategories/search/', views.workshopCategoriesSearch, name='workshopCategoriesSearch'),
    path('adminConfiguration/workshopsRegistrants/', views.workshopsRegistrants, name='workshopsRegistrants'),
    path('adminConfiguration/workshopsRegistrants/search', views.workshopsRegistrantsSearch, name='workshopsRegistrantsSearch'),
    path('adminConfiguration/registrationEmailMessage/<int:id>/edit', views.registrationEmailMessageEdit, name='registrationEmailMessageEdit'),
    path('adminConfiguration/registrationEmailMessage/<int:id>/delete', views.registrationEmailMessageDelete, name='registrationEmailMessageDelete'),
    path('adminConfiguration/registrationEmailMessage/<int:id>/preview/<int:workshop_id>', views.registrationEmailMessagePreview, name='registrationEmailMessagePreview'),
    path('adminConfiguration/registrationEmailMessage/new', views.registrationEmailMessageEdit, name='registrationEmailMessageNew'),
    path('adminConfiguration/registrationEmailMessages', views.registrationEmailMessages, name='registrationEmailMessages'),
    path('adminConfiguration/facilitator/<int:id>/edit', views.facilitatorEdit, name='facilitatorEdit'),
    path('adminConfiguration/facilitator/<int:id>/delete', views.facilitatorDelete, name='facilitatorDelete'),
    path('adminConfiguration/facilitator/new', views.facilitatorEdit, name='facilitatorNew'),
    path('adminConfiguration/facilitators/', views.facilitators, name='facilitators'),
    path('adminConfiguration/users/', views.users, name='users'),
    path('adminConfiguration/users/search', views.usersSearch, name='usersSearch'),
    path('search/clear/<str:session_var>', views.clearSearch, name='clearSearch'),
    path('adminConfiguration/users/upload', views.usersUpload, name='usersUpload'),
    path('adminConfiguration/users/export', views.usersExport, name='usersExport'),
    path('adminConfiguration/workPlace/<int:id>/edit', views.workPlaceEdit, name='workPlaceEdit'),
    path('adminConfiguration/workPlace/<int:id>/update', views.workPlaceUpdate, name='workPlaceUpdate'),
    path('adminConfiguration/workPlace/<int:id>/delete', views.workPlaceDelete, name='workPlaceDelete'),
    path('adminConfiguration/workPlace/new', views.workPlaceEdit, name='workPlaceNew'),
    path('adminConfiguration/workPlaces/search', views.workPlacesSearch, name='workPlacesSearch'),
    path('adminConfiguration/workPlaces/', views.workPlaces, name='workPlaces'),
    path('adminConfiguration/workPlaces/upload', views.workPlacesUpload, name='workPlacesUpload'),
    path('adminConfiguration/workPlaces/export', views.workPlacesExport, name='workPlacesExport'),
    path('adminConfiguration/teamMembers/', views.teamMembers, name='teamMembers'),
    path('adminConfiguration/teamMember/<int:id>/edit', views.teamMemberEdit, name='teamMemberEdit'),
    path('adminConfiguration/teamMember/<int:id>/delete', views.teamMemberDelete, name='teamMemberDelete'),
    path('adminConfiguration/teamMember/new', views.teamMemberEdit, name='teamMemberNew'),
    path('teamMember/<int:id>/view', views.teamMemberView, name='teamMemberView'),
    path('adminConfiguration/partners/', views.partners, name='partners'),
    path('adminConfiguration/partner/<int:id>/edit', views.partnerEdit, name='partnerEdit'),
    path('adminConfiguration/partner/<int:id>/delete', views.partnerDelete, name='partnerDelete'),
    path('adminConfiguration/partner/new', views.partnerEdit, name='partnerNew'),

    path('adminConfiguration/collaborators/', views.collaborators, name='collaborators'),
    path('adminConfiguration/collaborator/<int:id>/edit', views.collaboratorEdit, name='collaboratorEdit'),
    path('adminConfiguration/collaborator/<int:id>/delete', views.collaboratorDelete, name='collaboratorDelete'),
    path('adminConfiguration/collaborator/new', views.collaboratorEdit, name='collaboratorNew'),

    path('adminConfiguration/homepageBlocks/', views.homepageBlocks, name='homepageBlocks'),
    path('adminConfiguration/homepageBlock/<int:id>/edit', views.homepageBlockEdit, name='homepageBlockEdit'),
    path('adminConfiguration/homepageBlock/<int:id>/delete', views.homepageBlockDelete, name='homepageBlockDelete'),
    path('adminConfiguration/homepageBlock/new', views.homepageBlockEdit, name='homepageBlockNew'),

    path('adminConfiguration/standalonePages/', views.standalonePages, name='standalonePages'),
    path('adminConfiguration/standalonePage/<int:id>/edit', views.standalonePageEdit, name='standalonePageEdit'),
    path('adminConfiguration/standalonePage/<int:id>/delete', views.standalonePageDelete, name='standalonePageDelete'),
    path('adminConfiguration/standalonePage/<int:id>/copy', views.standalonePageCopy, name='standalonePageCopy'),
    path('standalonePage/<int:id>/view', views.standalonePageView, name='standalonePageIdView'),
    path('standalonePage/<str:url_alias>', views.standalonePageView, name='standalonePageAliasView'),
    path('adminConfiguration/standalonePage/new', views.standalonePageEdit, name='standalonePageNew'),

    path('adminConfiguration/surveys/', views.surveys, name='surveys'),
    path('adminConfiguration/surveys/search', views.surveysSearch, name='surveysSearch'),
    path('adminConfiguration/survey/<int:id>/edit', views.surveyEdit, name='surveyEdit'),
    path('adminConfiguration/survey/<int:id>/delete', views.surveyDelete, name='surveyDelete'),
    path('adminConfiguration/survey/<int:id>/copy', views.surveyCopy, name='surveyCopy'),
    path('adminConfiguration/survey/new', views.surveyEdit, name='surveyNew'),
    path('adminConfiguration/survey/<int:id>/submissions', views.surveySubmissions, name='surveySubmissions'),
    path('adminConfiguration/survey/<int:id>/submissions/search', views.surveySubmissionsSearch, name='surveySubmissionsSearch'),
    path('adminConfiguration/survey/<int:id>/submission/<uuid:submission_uuid>/view', views.surveySubmissionView, name='surveySubmissionView'),
    path('adminConfiguration/survey/<int:id>/submission/<uuid:submission_uuid>/view/modal', views.surveySubmissionViewModal, name='surveySubmissionViewModal'),
    path('adminConfiguration/survey/<int:id>/submission/<uuid:submission_uuid>/edit', views.surveySubmissionEdit, name='surveySubmissionEdit'),
    path('adminConfiguration/survey/<int:id>/submission/<uuid:submission_uuid>/delete', views.surveySubmissionDelete, name='surveySubmissionDelete'),
    path('adminConfiguration/survey/<int:survey_id>/submission/<uuid:submission_uuid>/export', views.surveySubmissionsExport, name='surveySubmissionsExport'),
    path('adminConfiguration/survey/<int:survey_id>/submissions/export', views.surveySubmissionsExport, name='surveySubmissionsExport'),

    path('adminConfiguration/survey/<int:survey_id>/surveyComponent/<int:id>/edit', views.surveyComponentEdit, name='surveyComponentEdit'),
    path('adminConfiguration/survey/<int:survey_id>/surveyComponent/<int:id>/delete', views.surveyComponentDelete, name='surveyComponentDelete'),
    path('adminConfiguration/survey/<int:survey_id>/surveyComponent/new', views.surveyComponentEdit, name='surveyComponentNew'),

    path('giveaway/info', views.giveawayInfo, name='giveawayInfo'),
    path('adminConfiguration/giveaways', views.giveaways, name='giveaways'),
    path('adminConfiguration/giveaways/search/', views.giveawaysSearch, name='giveawaysSearch'),
    path('adminConfiguration/giveaway/<int:id>/edit', views.giveawayEdit, name='giveawayEdit'),
    path('adminConfiguration/giveaway/<int:id>/delete', views.giveawayDelete, name='giveawayDelete'),
    path('adminConfiguration/giveaway/new', views.giveawayEdit, name='giveawayNew'),
    path('adminConfiguration/giveaway/requests', views.giveawayRequests, name='giveawayRequests'),
    path('adminConfiguration/giveaway/requests/search', views.giveawayRequestsSearch, name='giveawayRequestsSearch'),

    path('giveaway/request/<int:id>/edit', views.giveawayRequestEdit, name='giveawayRequestEdit'),
    path('giveaway/request/new', views.giveawayRequestEdit, name='giveawayRequestNew'),
    path('giveaway/<int:id>/view', views.giveawayView, name='giveawayView'),
    path('giveaway/<int:id>/max_quantity', views.get_giveaway_max_quantity, name='giveawayMaxQuantity'),
    path('adminConfiguration/giveaway/request/<int:id>/delete', views.giveawayRequestDelete, name='giveawayRequestDelete'),

    path('adminConfiguration/vignette/<int:id>/edit', views.vignetteEdit, name='vignetteEdit'),
    path('adminConfiguration/vignette/<int:id>/delete', views.vignetteDelete, name='vignetteDelete'),
    path('adminConfiguration/vignette/<int:id>/copy', views.vignetteCopy, name='vignetteCopy'),
    path('adminConfiguration/vignette/new', views.vignetteEdit, name='vignetteNew'),
    path('vignette/<int:id>/view/', views.vignetteView, name='vignetteView'),
    path('vignettes/search/<str:flag>', views.vignettesSearch, name='vignettesSearch'),
    path('vignettes/<str:flag>', views.vignettes, name='vignettes'),
    path('vignettes/', views.vignettes, name='vignettes'),

    path('survey/<int:survey_id>/submission/<uuid:submission_uuid>/page/<int:page_num>', views.surveySubmission, name='surveySubmission'),
    path('survey/<int:survey_id>/submission/new', views.surveySubmission, name='surveySubmissionNew'),
    path('baxter_box/info/', views.baxterBoxInfo, name='baxterBoxInfo'),
    path('baxter_box/search/', views.baxterBoxSearch, name='baxterBoxSearch'),
    path('about/bcse', views.aboutBCSE, name='aboutBCSE'),
    path('about/centers', views.aboutCenters, name='aboutCenters'),
    path('about/partners', views.aboutPartners, name='aboutPartners'),
    path('about/team', views.aboutTeam, name='aboutTeam'),
    path('about/contact', views.contactUs, name='contactUs'),
    path('about/terms', views.termsOfUse, name='termsOfUse'),
    path('about/teacherLeaders', views.aboutTeacherLeaders, name='aboutTeacherLeaders'),
    path('about/leadershipopportunities', views.teacherLeadershipOpportunities, name='teacherLeadershipOpportunities'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('subscribe/email', views.subscribeFromEmail, name='subscribeFromEmail'),
    path('load_equipment_options/<int:activity_id>/', views.load_equipment_options, name='load_activity_equipment_options'),
    path('load_equipment_options/', views.load_equipment_options, name='load_all_equipment_options')


]
